# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

#name: Java CI with Gradle

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 8
#      uses: actions/setup-java@v1
#      with:
#        java-version: '8'
#        
#    - name: Grant execute permission for gradlew
#      run: chmod +x ./gradlew
#        
#    - name: Build with Gradle
#      run: ./gradlew build
#        
#    # 압축파일 형태로 전달
#    - name: Make zip file
#      run: zip -r ./makecake.zip .
#      
#    # S3 Bucket으로 전달
#    - name: AWS S3 Upload
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: |
#        aws s3 cp \
#        --region ap-northeast-2 \
#        --acl private ./makecake.zip s3://devssk/
#    # Deploy
#    - name: Deploy
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: |
#        aws deploy create-deployment \
#        --application-name makecake \
#        --deployment-group-name makecake \
#        --file-exists-behavior OVERWRITE \
#        --s3-location bucket=devssk,bundleType=zip,key=makecake.zip \
#        --region ap-northeast-2
